#!/usr/bin/env ruby

require 'bundler/setup'
require 'assert_zone'
require 'optparse'

options = {
  rspec_flags: [],
  use_local_resolver: false
}

OptionParser.new do |opts|
  opts.banner = "Usage: assert_zone ZONE_FILE [NAMESERVER] [options]"
  opts.on('--color', 'Use color') do |v|
    options[:rspec_flags] << '--color'
  end
  opts.on('--use-local-resolver', 'Use local resolver settings instead of explicit nameserver') do |v|
    options[:use_local_resolver] = true
  end
  opts.on('--skip-ns', 'Skip NS records') do |v|
    options[:skip_ns] = true
  end
  opts.on('--skip-soa', 'Skip SOA record') do |v|
    options[:skip_soa] = true
  end
  opts.on_tail('-h', '--help', 'Show this message') do
    puts opts
    exit
  end
  opts.on_tail('--version', 'Show version') do
    puts "assert_zone #{AssertZone::VERSION}"
    exit
  end
end.parse!

AssertZone.run(ARGV[0], nameserver: ARGV[1], rspec_flags: options[:rspec_flags], use_local_resolver: options[:use_local_resolver])
